export const projectsData = [
  {
    name: "qazini",
    nameSlug: "qazini",
    summary: "Job search helper that uses RapidAPI with graphQL",
    gradientStyle:
      "bg-gradient-to-br from-[#FFD3EB] via-[#ff98d0] to-[#ff229a]",
    fullDescription:
      "NyumbaHub is a vacant houses finding service based in Kenya. Itincludes a non-relational database MongoDB, Node/Express.js RESTful API hosted as a serverless function, and a React frontend where the  house properties data is served to. The API employs the MVC design pattern. Using mongoose ODM (Object-Data Modelling), there are defined schemas for the 4 models used throughout the application. Public routes are available to all users while private routes are protected with JSON Web Token (JWT) and either require signing in to access service or can only be accessed by privileged users.",
    websiteLink: "https://qazini-jobs.vercel.app",
    gitHubLink: "https://github.com/pptrgi/qazini-jobs",
    images: [],
    technologies: ["Graphql", "Node.js", "Express.js", "React.js", "RapidAPI"],
    features: [
      "Fully responsive",
      "Private and open routes",
      "Breadcrumbs",
      "Dynamic pages titling",
      "Privacy",
      "Policy",
    ],
  },
  {
    name: "nyumbaHub",
    nameSlug: "nyumbahub",
    summary: "Job search helper that uses RapidAPI with graphQL",
    gradientStyle: "bg-gradient-to-bl to-[#00aeff] from-[#1e73be]",
    fullDescription:
      "NyumbaHub is a vacant houses finding service based in Kenya. Itincludes a non-relational database MongoDB, Node/Express.js RESTful API hosted as a serverless function, and a React frontend where the  house properties data is served to. The API employs the MVC design pattern. Using mongoose ODM (Object-Data Modelling), there are defined schemas for the 4 models used throughout the application. Public routes are available to all users while private routes are protected with JSON Web Token (JWT) and either require signing in to access service or can only be accessed by privileged users.",
    websiteLink: "https://qazini-jobs.vercel.app",
    gitHubLink: "https://github.com/pptrgi/qazini-jobs",
    images: [],
    technologies: ["Graphql", "Node.js", "Express.js", "React.js", "RapidAPI"],
    features: [
      "Fully responsive",
      "Private and open routes",
      "Breadcrumbs",
      "Dynamic pages titling",
      "Privacy",
      "Policy",
    ],
  },
  {
    name: "seedlings by mwalim",
    nameSlug: "seedlingsbymwalim",
    summary: "Job search helper that uses RapidAPI with graphQL",
    gradientStyle: "bg-gradient-to-r from-[#5267DF] to-[#9fadfd]",
    fullDescription:
      "NyumbaHub is a vacant houses finding service based in Kenya. Itincludes a non-relational database MongoDB, Node/Express.js RESTful API hosted as a serverless function, and a React frontend where the  house properties data is served to. The API employs the MVC design pattern. Using mongoose ODM (Object-Data Modelling), there are defined schemas for the 4 models used throughout the application. Public routes are available to all users while private routes are protected with JSON Web Token (JWT) and either require signing in to access service or can only be accessed by privileged users.",
    websiteLink: "https://qazini-jobs.vercel.app",
    gitHubLink: "https://github.com/pptrgi/qazini-jobs",
    images: [],
    technologies: ["Graphql", "Node.js", "Express.js", "React.js", "RapidAPI"],
    features: [
      "Fully responsive",
      "Private and open routes",
      "Breadcrumbs",
      "Dynamic pages titling",
      "Privacy",
      "Policy",
    ],
  },
  {
    name: "personal website",
    nameSlug: "personalwebsite",
    summary: "Job search helper that uses RapidAPI with graphQL",
    gradientStyle: "bg-gradient-to-r from-titleColor to-titleColorDark",
    fullDescription:
      "NyumbaHub is a vacant houses finding service based in Kenya. Itincludes a non-relational database MongoDB, Node/Express.js RESTful API hosted as a serverless function, and a React frontend where the  house properties data is served to. The API employs the MVC design pattern. Using mongoose ODM (Object-Data Modelling), there are defined schemas for the 4 models used throughout the application. Public routes are available to all users while private routes are protected with JSON Web Token (JWT) and either require signing in to access service or can only be accessed by privileged users.",
    websiteLink: "https://qazini-jobs.vercel.app",
    gitHubLink: "https://github.com/pptrgi/qazini-jobs",
    images: [],
    technologies: ["Graphql", "Node.js", "Express.js", "React.js", "RapidAPI"],
    features: [
      "Fully responsive",
      "Private and open routes",
      "Breadcrumbs",
      "Dynamic pages titling",
      "Privacy",
      "Policy",
    ],
  },
];
